{% set name = "snowflake-ml-python" %}
{% set version = "1.8.5" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowflake_ml_python-{{ version }}.tar.gz
  sha256: c02e02e071dca03bb183aeae397aaa80b305de46ad08c931b0b833e34dd24f87
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolatio
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - absl-py >=0.15,<2
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<5
    - cachetools >=3.1.1,<6
    - cloudpickle >=2.0.0
    - cryptography
    - fsspec >=2024.6.1,<2026
    - importlib_resources >=6.1.1,<7
    - numpy >=1.23,<2
    - packaging >=20.9,<25
    - pandas >=1.0.0,<3
    - pyarrow
    - pydantic >=2.8.2,<3
    - pyjwt >=2.0.0,<3
    - pytimeparse >=1.1.8,<2
    - pyyaml >=6.0,<7
    - requests
    - retrying >=1.3.3,<2
    - s3fs >=2024.6.1,<2026
    - scikit-learn <1.6
    - scipy >=1.9,<2
    - shap >=0.46.0,<1
    - snowflake-connector-python >=3.12.0,<4
    - snowflake-snowpark-python >=1.17.0,<2,!=1.26.0
    - snowflake.core >=1.0.2,<2
    - sqlparse >=0.4,<1
    - typing-extensions >=4.1.0,<5
    - python >={{ python_min }},<3.13.0a0
  run_constrained:
    - catboost >=1.2.0,<2
    - keras >=2.0.0,<4
    - lightgbm >=4.1.0,<5
    - mlflow >=2.16.0,<3
    - pytorch >=2.0.1,<3
    - sentence-transformers >=2.7.0,<4
    - sentencepiece >=0.1.95,<0.2.0
    - tensorflow >=2.17.0,<3
    - tokenizers >=0.15.1,<1
    - torchdata >=0.4,<1
    - transformers >=4.39.3,<5
    - xgboost >=1.7.3,<3
test:
  imports:
    - snowflake.cortex
    - snowflake.ml
    - snowflake.ml.modeling
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  description: |
    Snowflake ML client Library is used for interacting with Snowflake to build machine learning solutions.
    Functionalities include feature engineering, modeling, model management, deployment, etc
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://github.com/snowflakedb/snowflake-ml-python/blob/main/README.md
  home: https://github.com/snowflakedb/snowflake-ml-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake ML Library
extra:
  recipe-maintainers:
    - sfc-gh-pramachandran
    - sfc-gh-rsureshbabu
    - sfc-gh-hayu
    - sfc-gh-aponnusamy
    - sfc-gh-thoyt
    - sfc-gh-sdas
    - sfc-gh-wzhao
    - sfc-gh-pdorairaj
    - sfc-gh-srudenko
